# Generated by Django 3.1 on 2020-08-14 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('number', models.CharField(max_length=16, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('stable', models.CharField(max_length=100, verbose_name='Estado')),
                ('zipcode', models.CharField(max_length=8, verbose_name='CEP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
